---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

namePrefix: prod-

configMapGenerator:
  - name: fully-managed-connectors-consumer-app-properties-map
    files:
      - application.yaml

images:
  - name: image_placeholder
    newName: docker-prod.artifactory.michelin.com/kfe/fully-managed-connectors-consumer/fully-managed-connectors-consumer
    newTag: 1.0

generators:
  - secret-generator.yml
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
