spring:
  kafka:
    bootstrap-servers: pkc-mvjp7.northeurope.azure.confluent.cloud:9092
    consumer:
      group-id: kfe.fully-managed-connectors-consumer-dev
connect:
  logs:
    topic: confluent-connect-log-events
