---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dkfegbl0

commonLabels:
  environment: dev

namePrefix: dev-

configMapGenerator:
  - name: fully-managed-connectors-consumer-app-properties-map
    files:
      - application.yaml

images:
  - name: image_placeholder
    newName: hip-mess-mass-docker-snapshot.artifactory.michelin.com/kfe/fully-managed-connectors-consumer
    newTag: 1.0-SNAPSHOT

generators:
  - secret-generator.yml
patchesStrategicMerge:
  - deployment.yaml
resources:
  - ../../base
